# Generated by Django 5.1.7 on 2025-03-28 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_asegurados', '0004_alter_diagnosticos_options_remove_diagnosticos_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_documento', models.CharField(max_length=50, unique=True)),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('tipo_documento', models.CharField(blank=True, max_length=10, null=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('tamaño', models.CharField(editable=False, max_length=20)),
                ('ultima_modificacion', models.DateField(auto_now=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('historial', models.TextField(blank=True, null=True)),
                ('datos_xml', models.JSONField(blank=True, null=True)),
                ('id_asegurado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_asegurados.asegurado')),
                ('id_poliza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor_asegurados.poliza')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
