# Generated by Django 5.1.7 on 2025-03-28 15:17

import gestor_documentos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='tipo_descripcion',
            field=models.CharField(choices=[('desglose', 'Desglose'), ('endoso', 'Endoso'), ('estado_cuenta', 'Estado de Cuenta'), ('factura', 'Factura'), ('formato_reembolso', 'Formato de Reembolso'), ('id_oficial', 'ID Oficial'), ('informe_medico', 'Informe Médico'), ('plan_tratamiento', 'Plan de Tratamiento'), ('poliza', 'Póliza'), ('receta', 'Receta'), ('resultados_estudios', 'Resultados de Estudios'), ('ticket_compra', 'Ticket de Compra'), ('otro', 'Otro')], default='otro', max_length=20, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='id_documento',
            field=models.CharField(default=gestor_documentos.models.generar_id_documento, max_length=50, unique=True),
        ),
    ]
