# Generated by Django 5.1.7 on 2025-03-28 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gestor_asegurados', '0005_delete_reclamacion'),
        ('gestor_documentos', '0002_documento_tipo_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoReembolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('factura', 'Factura'), ('receta', 'Receta Médica'), ('estudios', 'Estudios'), ('informe', 'Informe Médico'), ('otro', 'Otro')], max_length=20)),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_documentos.documento')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaReclamacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Importe de la factura')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_documentos.documento')),
            ],
            options={
                'verbose_name': 'Factura de Reclamación',
                'verbose_name_plural': 'Facturas de Reclamaciones',
            },
        ),
        migrations.CreateModel(
            name='Reclamacion',
            fields=[
                ('id_reclamacion', models.AutoField(primary_key=True, serialize=False)),
                ('inicial_complementaria', models.BooleanField(default=False, help_text='Marcar si esta reclamación es complementaria a una anterior', verbose_name='¿Es complementaria?')),
                ('cantidad_partidas', models.IntegerField(help_text='Número de partidas en la reclamación', verbose_name='Cantidad de partidas')),
                ('abierta', models.BooleanField(default=True, help_text='Indica si la reclamación sigue abierta o ya está cerrada', verbose_name='¿Reclamación abierta?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('facturas', models.ManyToManyField(related_name='reclamaciones', through='gestor_reembolsos.FacturaReclamacion', to='gestor_documentos.documento')),
                ('id_diagnostico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_asegurados.diagnosticos')),
            ],
            options={
                'verbose_name': 'Reclamación',
                'verbose_name_plural': 'Reclamaciones',
            },
        ),
        migrations.AddField(
            model_name='facturareclamacion',
            name='reclamacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_reembolsos.reclamacion'),
        ),
        migrations.CreateModel(
            name='Reembolso',
            fields=[
                ('id_reembolso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En Revisión'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('comentarios', models.TextField(blank=True, null=True)),
                ('asegurado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_asegurados.asegurado')),
                ('documentos', models.ManyToManyField(through='gestor_reembolsos.DocumentoReembolso', to='gestor_documentos.documento')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_asegurados.poliza')),
                ('usuario_creacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='reclamacion',
            name='reembolso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reclamaciones', to='gestor_reembolsos.reembolso'),
        ),
        migrations.AddField(
            model_name='documentoreembolso',
            name='reembolso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestor_reembolsos.reembolso'),
        ),
        migrations.AlterUniqueTogether(
            name='facturareclamacion',
            unique_together={('reclamacion', 'documento')},
        ),
        migrations.AlterUniqueTogether(
            name='documentoreembolso',
            unique_together={('reembolso', 'documento')},
        ),
    ]
