# Generated by Django 5.1.7 on 2025-03-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_reembolsos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reembolso',
            name='pdf_generado',
            field=models.FileField(blank=True, null=True, upload_to='reembolsos/', verbose_name='PDF del reembolso'),
        ),
    ]
