# Generated by Django 5.1.7 on 2025-03-27 21:15

import gestor_asegurados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='fecha_nacimiento',
            field=gestor_asegurados.models.MexicanDateField(),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=10),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='titular_conyuge_dependiente',
            field=models.CharField(choices=[('Titular', 'Titular'), ('Conyuge', 'Conyuge'), ('Dependiente', 'Dependiente')], default='Titular', max_length=15),
        ),
    ]
