# Generated by Django 5.1.7 on 2025-03-27 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0002_alter_asegurado_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asegurado',
            name='id_asegurado',
            field=models.CharField(help_text='Identificador único alfanumérico del asegurado', max_length=50, primary_key=True, serialize=False),
        ),
    ]
