# Generated by Django 5.1.7 on 2025-03-27 22:34

import gestor_asegurados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0003_alter_asegurado_id_asegurado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticos',
            options={'verbose_name': 'Diagnóstico', 'verbose_name_plural': 'Diagnósticos'},
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='id',
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_inicio_padecimiento',
            field=gestor_asegurados.models.MexicanDateField(),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_primera_atencion',
            field=gestor_asegurados.models.MexicanDateField(),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='id_diagnostico',
            field=models.CharField(help_text='Identificador único alfanumérico del diagnóstico', max_length=50, primary_key=True, serialize=False),
        ),
    ]
