# Generated by Django 5.1.7 on 2025-03-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0004_alter_diagnosticos_options_remove_diagnosticos_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reclamacion',
        ),
    ]
