# Generated by Django 5.1.7 on 2025-03-28 21:36

import django.db.models.deletion
import django.utils.timezone
import gestor_asegurados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0005_delete_reclamacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticoAsegurado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_padecimiento', gestor_asegurados.models.MexicanDateField()),
                ('fecha_primera_atencion', gestor_asegurados.models.MexicanDateField()),
                ('asegurado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='diagnosticos_relacionados', to='gestor_asegurados.asegurado')),
            ],
        ),
        migrations.DeleteModel(
            name='Diagnostico',
        ),
        migrations.RemoveField(
            model_name='diagnosticos',
            name='id_asegurado',
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='fecha_creacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_inicio_padecimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_primera_atencion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticoasegurado',
            name='diagnostico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestor_asegurados.diagnosticos'),
        ),
        migrations.AddField(
            model_name='diagnosticos',
            name='asegurados',
            field=models.ManyToManyField(related_name='diagnosticos', through='gestor_asegurados.DiagnosticoAsegurado', to='gestor_asegurados.asegurado'),
        ),
        migrations.AlterUniqueTogether(
            name='diagnosticoasegurado',
            unique_together={('diagnostico', 'asegurado')},
        ),
    ]
