# Generated by Django 5.1.7 on 2025-03-31 23:26

import gestor_asegurados.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_asegurados', '0006_diagnosticoasegurado_delete_diagnostico_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diagnosticos',
            options={'verbose_name': 'Diagnostico', 'verbose_name_plural': 'Diagnosticos'},
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_inicio_padecimiento',
            field=gestor_asegurados.models.MexicanDateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnosticos',
            name='fecha_primera_atencion',
            field=gestor_asegurados.models.MexicanDateField(default=None),
            preserve_default=False,
        ),
    ]
